### PR TITLE
More fluent Ruby API

### PR DESCRIPTION
**Pull request by keleshev**

### CODE REVIEW

**Comment by keleshev** [comment]
The aim of this PR is to make Quark-to-Ruby interface more convenient for Ruby developers, by allowing them traversing modules with `::` operators as they do, and to allow Ruby-esque naming conventions. So, now instead of:

```
Quark.hello_namespace.hello_class.new
```

a Ruby developer could write:

```
Quark::HelloNamespace::HelloClass.new
```

This makes the identifier scheme match the rosetta stone.

**Comment by keleshev** [comment]
See how this affected helloRPC here:

https://github.com/datawire/quark/pull/119/commits/fd3599777d05ea3c0e9b0a305bc3a02a24c1fabe

FYI, the old scheme still works, and is relied upon internally.

**Comment by keleshev** [comment]
@brikelly @bozzzzo your feedback is appreciated

**Comment by bozzzzo** [comment]
Nice!

**Pull request merged**
