### PR TITLE
Enable pyflakes, via flake8

### PR DESCRIPTION
**Pull request by itamarst**
Using `flake8` tool will allow us to add PEP-8 checks later.

This:
1. Enables some quick checks for potential bugs.
2. Fixes a bunch of imports, unused variables, and one actual bug.
3. Adds `absolute_import` to a bunch of modules; it is default on Python 3 and a good idea in general.

### CODE REVIEW

**Comment by itamarst** [comment]
(Still haven't finished running tests locally and fixing what broke, just a placeholder until I've fixed everything).

**Comment by keleshev** [comment]
How about using py.test plugin for pyflakes instead?

* https://pypi.python.org/pypi/pytest-flakes

This has an advantage that it automatically becomes part of every developer workflow, not only through CI or Docker. What do you think?

Otherwise looks awesome.

**Comment by itamarst** [comment]
Ah, good idea (probably want pytest-flake8, but same idea). Will go try that.

In general I recommend setting up flake8 in your editor; on Emacs I use elpy, but I assume pretty much any decent editor has some way to do it.

**Comment by keleshev** [comment]
I've been using [syntastic](https://github.com/scrooloose/syntastic) with flakes8 if anyone also uses Vim

**Pull request merged**
